/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BasicNft } from "./BasicNft";
export type { HuskyCoin } from "./HuskyCoin";
export type { NFTDutchAuction_ERC20Bids } from "./NFTDutchAuction_ERC20Bids";
