/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftDutchAuctionErc20BidsSol from "./NFTDutchAuction_ERC20Bids.sol";
export type { nftDutchAuctionErc20BidsSol };
export type { BasicNft } from "./BasicNft";
export type { HuskyCoin } from "./HuskyCoin";
export type { NFTDutchAuction } from "./NFTDutchAuction";
