name: Regression test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
env:
  Sha: ${{ github.event.pull_request.head.sha }}
      

jobs:
  benchmark:
    name: Run Benchmarks on PR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'
      - run: echo 'go version  $(go version)'
  update-benchmark-result:
    name: Update latest benchmark result
    needs: benchmark
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update benchmark result
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-result_${{ env.Sha }}
          path: ${{ github.workspace }}/results.json
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            event: push
            run_number: 34
            name: benchmark-result_${{ env.Sha }}
            name_is_regexp: true
            if_no_artifact_found: fail
        