name: Regression test

on:
  pull_request:
    branches:
      - main
env:
  Sha: ${{ github.event.pull_request.head.sha }}
      

jobs:
  benchmark:
    name: Run Benchmarks on PR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'
      - run: make
      # - name: Run benchmark
      #   run: make benchmarks-perf-test
      # - run: cd benchmark/performanceTest && cat output/results.json
  update-benchmark-result:
    name: Update latest benchmark result
    needs: benchmark
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update benchmark result
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-result_${{ env.Sha }}
          path: results.json
  fetch_previous_json_files:
    runs-on: ubuntu-latest
    # needs: update-benchmark-result
    steps:
      - uses: actions/checkout@v3
      - name: Download previous artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: benchmark-result_${{ env.Sha }}
        #   workflow_conclusion: completed
        #   branch: main
        #   event: push
          # path: ${{ github.workspace }}/previous
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # repo: ${{ github.repository }}
          # path: ${{ github.workspace }}
          # search_artifacts: true
        