name: Regression test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
env:
  Sha: ${{ github.event.pull_request.head.sha }}
      

jobs:
  benchmark:
    name: Run Benchmarks on PR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'
      - name: Compare Benchmarks
        id: run-compare
        run: |
         sudo chmod +x ${{ github.workspace }}/scripts/check_regression.sh
         if sudo ${{ github.workspace }}/scripts/check_regression.sh ${{ github.workspace }}/past.json ${{ github.workspace }}/current.json; then
          echo "Comparison successful. All P90 values are within the acceptable range."
         else
            echo "Comparison failed. Current P90 values exceed 110% of the corresponding past values."
            echo "Adding a comment to the Pull Request."
            echo "::set-output name=regression-detected::true"
            echo "regression-detected=true" >> "$GITHUB_ENV"
         fi
      - name: Comment on PR if regression detected
        if: steps.run-compare.outputs.regression-detected == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `
              :warning: **Regression Detected** :warning:

              The benchmark comparison indicates that there has been a performance regression.
              Please investigate and address the issue.
            `;
            core.setFailed(comment);